---
- name: Install Nginx
  hosts: vm-servers
  remote_user: root
  # become: yes
  # become_method: sudo

  roles:
    - common-software
    - nginx
    - geerlingguy.java
    - geerlingguy.elasticsearch
    - geerlingguy.logstash
    - geerlingguy.filebeat
    - geerlingguy.kibana
