---
- name: Install Nginx
  hosts: vm-servers
  remote_user: root
  # become: yes
  # become_method: sudo
  
  roles:
    - common-software
    # - nginx
    - role: geerlingguy.java
      java_packages:
        - java-1.8.0-openjdk
    - geerlingguy.elasticsearch
    - geerlingguy.logstash
    - geerlingguy.filebeat
